### ISSUE TITLE
this modules functions are an almost exact duplicate of another ps module

### ISSUE THREAD

**Issue by TheBigBear** [MSEndpointMgr/EDGEProfiles#3]
Hi @mardahl 

the two functions in this module are (almost) exactly same-named duplicates of one another ps module doing the 'same' thing by Alex Laurie? 

And isn't there a PS module building and naming rule that says it should be singular and not plural (i.e. profile not profiles?) 

https://www.powershellgallery.com/packages/EdgeBackupandRestore/0.0.5

```
EdgeBackupandRestore         -> EDGEProfiles
Backup-EdgeProfile           -> Backup-EDGEProfiles 
Restore-EdgeProfile          -> Restore-EDGEProfiles
```

**Comment by mardahl** [comment]
Hi TheBigBear,

Thank you for your feedback.

If I had known about that module, I would have simply used that, instead of spending a late night coding this just for fun.

That being said, I am aware of the whole plurals debate. The module is, however, designed to backup profiles in the plural sense, so I choose to keep it plural. 
Pull requests are more than welcome if you have improvements.
